server:
  port: 4001

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka01:6001/eureka,http://eureka02:6002/eureka,http://eureka03:6003/eureka
  instance:
    instance-id: zuul-gateway
    prefer-ip-address: true



zuul:
  routes:
    a.serviceId: provider
    a.path: /b/**
  ignored-services: "*"
  prefix: /wu
#  ignored-services: provider